### ISSUE TITLE
Could not translate host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by tgamal** [mumoshu/kube-airflow#10]
I tried to deploy kube-airflow on a kubernetes cluster running ubnuntu 14.04. When I run the example airflow command "airflow backfill tutorial -s ---", I get the following error:

File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known.

I checked the pods and postgres-2280134284-e2j1r pod seems to be running. Not sure whats wrong, any help is much appreciated 

Note that I did not install kubernetes using minkube, I installed the kubernetes manually on ubuntu using [this guide](https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/)

**Comment by gppeixoto** [comment]
It looks like you don't have a Service properly set up, which explains why it couldn't make a lookup for postgres on the DNS. You should create a Service for the Postgres pod in order to other applications find it

**Comment by markqiu** [comment]
Thank you very much!

**Comment by kevincvlam** [comment]
I am also encountering this error occasionally, but it's after the getting all the pods up and running for some time. 

I am running a kube-airflow setup inside of GKE on Google. I'm wondering if it could be caused by flakinesss with the KubeAPI server?

**Comment by chribsen** [comment]
I'm also experiencing this problem after some time on the `web` deployment. A temporary solution is to add the following health check on the deployment:
```
livenessProbe:
          httpGet:
            path: /
            port: <container-port>
          initialDelaySeconds: 240
          periodSeconds: 30
```
If the given `web` pod doesn't respond k8s will automatically restart it.
