### ISSUE TITLE
helm installation fail

### ISSUE THREAD

**Issue by lvcz** [mumoshu/kube-airflow#37]
helm upgrade -f /home/pathto/airflow/values.yaml \
             --install \
             --debug \
             airflow \
             ./airflow
[debug] Created tunnel using local port: '43327'

[debug] SERVER: "127.0.0.1:43327"

Error: found in requirements.yaml, but missing in charts/ directory: postgresql, redis
Makefile:35: recipe for target 'helm-install' failed
make: *** [helm-install] Error 1

**Comment by WakeupTsai** [comment]
Run `helm dependency update` in ./airflow to get the dependencies before run `make helm-install`
