### ISSUE TITLE
please update dockerfile (and maybe entrypoint.sh)

### ISSUE THREAD

**Issue by ToGoBananas** [mumoshu/kube-airflow#4]
Can you update repository?
seems like your github repository behind docker hub image

**Comment by mumoshu** [comment]
Hi @ToGoBananas, the git repo seems to be up to date with my local one!
Could you inform me if there's anything specific you've thought to be missing in the repo?

**Comment by tkaymak** [comment]
I think he means that you are still using 1.7 while the docker image is on 1.8 
https://github.com/puckel/docker-airflow/commit/748c00915734027ddebd3b6e8e9f39e9ec776d46

**Comment by ToGoBananas** [comment]
as far as I can remember, I was not able to create working image using dockerfile and entrypoint from your repo(but docker hub image worked fine)

 I created my own image based on python3.6 and airflow 1.9dev, so I think I can close this issue
